services:
  - type: web
    name: hhk-digital
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn hhk_core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DEBUG
        value: "True"
      - key: DJANGO_SETTINGS_MODULE
        value: hhk_core.settings
      - key: SECRET_KEY
        generateValue: true
