# Generated by Django 6.0.4 on 2026-04-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_order_voucher_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=100, verbose_name='Số lượng tồn kho'),
        ),
    ]
