# Generated by Django 6.0.3 on 2026-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Hà Nội', 'TP. Hà Nội'), ('Đà Nẵng', 'TP. Đà Nẵng'), ('Hải Phòng', 'TP. Hải Phòng'), ('Cần Thơ', 'TP. Cần Thơ'), ('Bình Dương', 'Bình Dương'), ('Đồng Nai', 'Đồng Nai'), ('Long An', 'Long An'), ('Khác', 'Tỉnh thành khác')], default='Hồ Chí Minh', max_length=200, verbose_name='Thành phố'),
        ),
    ]
